---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
- type: directory
  path: content
  label: Pages
  create: documents
  match: "*"
  templates:
  - homepage
- type: heading
  label: Catalogs
- type: directory
  path: content/faqs
  label: FAQs
  create: documents
  match: "**/*"
  templates:
  - faq
- type: directory
  path: content/products
  label: Products
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: content/ctas
  label: CTAs
  create: documents
  match: "**/*"
  templates:
  - cta
upload_dir: assets/uploads
public_path: _nuxt/assets/uploads
front_matter_path: "~/assets/uploads"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
