---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
- type: directory
  path: content
  label: Pages
  create: documents
  match: "*"
  templates:
  - homepage
- type: directory
  path: content/products
  label: Products
  create: documents
  match: "**/*"
  templates:
  - product
upload_dir: assets/images
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  instant_preview_command: yarn forestry-preview
