---
label: Product
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: categories
  type: tag_list
  default:
  - Quests
  - Extra Large
  - Tech
  - Exploration
  - Magic
  label: Categories
- name: cats
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: simple
      section: products
    options:
    - one
    - two
    - three
  label: Cats
pages:
- content/products/aof5.md
