---
label: Product
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: categories
  type: select
  default: []
  config:
    required: false
    options:
    - Quests
    - Extra Large
    - Tech
    - Magic
    - Exploration
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Categories
pages:
- content/products/aof5.md
