---
label: Product
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: type
  type: select
  default: Modpack
  config:
    required: false
    options:
    - Modpack
    - Mod
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
- name: images
  type: field_group
  config: {}
  fields:
  - name: 1x
    type: file
    config:
      maxSize: 64
    label: 1x
  - name: 2x
    type: file
    config:
      maxSize: 64
    label: 2x
  label: Images
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: categories
  type: include
  config: {}
  template: categories
  label: Categories
- name: button
  type: field_group
  config: {}
  fields:
  - name: button
    type: include
    config: {}
    template: button
    label: Button
  label: Button
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
