---
label: Products
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: something
  type: blocks
  label: something
  template_types:
  - product
  config:
    min: 
    max: 
