---
label: Product
hide_body: true
fields:
- name: release_date
  type: datetime
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  label: Release date
  default: now
- name: title
  type: text
  config:
    required: false
  label: Title
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: text
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Text
- name: categories
  type: include
  config: {}
  template: categories
  label: Categories
- name: type
  type: select
  default: Modpack
  config:
    required: false
    options:
    - Modpack
    - Mod
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
- name: mod_count
  type: number
  label: Mod count
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
  showOnly:
    field: type
    value: Modpack
- name: button
  type: include
  config: {}
  template: button
  label: Button
- name: color
  type: include
  config: {}
  template: color
  label: Color
pages:
- content/products/aof3.md
- content/products/aof4.md
